### ISSUE TITLE
[Support] How could we test non existing element ?

### ISSUE THREAD

**Issue by jogelin** [NicholasBoll/cypress-pipe#28]
Hey, I am in the process of "making my utilities more chainable and reusable" and your library helped me a lot in the chainable syntax using functions.

I am doing that mainly for shared UI components and it works well to access to elements but I have an issue when I want to test the nonexistence of an element.

Let me illustrate by an example:

```
const getFirst = $el => $el.find('#first')

cy.get('body')
  .pipe(getFirst) 
  .should('not.exist')
```
This fails because it is waiting for the `'#first'` but I want to validate it does not exist

if I don't use the pipe function:
```
cy.get('body')
  .get('#first')
  .should('not.exist')
```
It works !! But I would like to use the `pipe` function because I would like to re-use it

**Comment by NicholasBoll** [comment]
I've added a specific test here to verify it does work with no coding changes:

```ts
      it('should not fail with a missing selector when non-existance assertion is used', () => {

        const thisWillFail = $el => $el.find('#wontfind')
        cy.get('body')
          .pipe(thisWillFail, { timeout: 50 })
          .should('not.exist')
      })
```

Can you verify your use-case fails? I have another user using the DOM Testing Library which doesn't work because `get*` queries in the DOM Testing Library throw errors instead of return empty jQuery node lists. Cypress has a `cy.verifyUpcomingAssertions` that `cypress-pipe` uses the properly handles the `should('not.exists')` assertion. If your command has no assertion following it, existence is used. If the subject is a jQuery node list, "existence" means there's at least 1 element in the list. `not.exist` changes that to test exactly 0 items in the list. DOM testing library doesn't work by using jQuery node lists and therefore doesn't handle the `not.exist` case.

`cypress-pipe` could be updated to handle this case specifically by looking on the Cypress change for assertions for the `not.exist` assertion type and swallow the DOM testing library non-existence error in this case.
